runtime: python
env: flex
entrypoint: gunicorn -b :$PORT --worker-class eventlet -w 1 app:app

runtime_config:
    python_version: 3.7

handlers:
- url: /.*
  script: app.app

network:
  session_affinity: true
